name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version-file: go.mod
      - name: Tests
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic -coverpkg="$(go list ./... | tr '\n' , | sed 's/,$//')" ./...
          go tool cover -func=coverage.txt
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5.5.2
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
      - run: go vet ./...
